"use strict";

/**
 * Structural data for the 13 modules that have a full guide.
 * Translatable prose lives in modules.text.js; only labels and geometry live here.
 *
 * Every content block is optional on purpose. The detail page renders a section
 * only when its data is present, because the source material is uneven: some
 * modules document two wiring figures, some one, the power adapter documents
 * charging states and has no program at all.
 *
 * video.id and program.hex stay null until the material is published, and the
 * page simply leaves those blocks out rather than announcing what is missing.
 * See README.md, "Publishing module material", and PENDIENTES.md.
 */

const VIDEO_PROVIDER = "cloudflare";

/** Cloudflare Stream customer subdomain, from the Stream dashboard embed code. */
const CLOUDFLARE_SUBDOMAIN = "";

/**
 * A video counts as published only when the provider is configured too, so an
 * id pasted in before the Stream subdomain leaves the section out rather than
 * showing a broken player.
 */
function isVideoPublished(video) {
  if (!video || !video.id) return false;
  return VIDEO_PROVIDER !== "cloudflare" || Boolean(CLOUDFLARE_SUBDOMAIN);
}

/**
 * Only the colours the source manual states explicitly. Wires whose colour the
 * manual does not name are listed without a swatch, so the legend never invents
 * a colour a teacher could follow into a miswiring.
 */
const WIRE = {
  red: "#d0342c",
  black: "#1a1a1a",
  brown: "#6b4423",
  yellow: "#f2c230",
  green: "#1f8a4c",
};

const MODULES = [
  {
    slug: "servo-180",
    componentKey: "servomotor180",
    kit: "physical",
    role: "actuator",
    video: { id: null, driveId: "1WEO_X4uEb2F1tgsp8U2hYModXhbsIjms" },
    program: {
      hex: null,
      blocks: "guides/servo-180/blocks.png",
      driveId: "1jz1pQOAguZhga8yos21ieiVfcjclIo6_",
    },
    wiring: {
      order: "guides/servo-180/wiring-order.jpg",
      done: "guides/servo-180/wiring-done.jpg",
      wires: [
        { color: WIRE.red, key: "vcc" },
        { color: WIRE.brown, key: "gnd" },
        { color: WIRE.yellow, key: "signal" },
      ],
    },
    parts: {
      image: "guides/servo-180/parts.jpg",
      list: [
        { qty: 1, key: "microbitV2" },
        { qty: 1, key: "downloadCable" },
        { qty: 3, key: "alligatorClip" },
        { qty: 3, key: "jumperMM" },
        { qty: 1, key: "servo180" },
      ],
    },
    troubleshootingStatus: "draft",
  },
  {
    slug: "rgb-led-strip",
    componentKey: "rgbLedStrip",
    kit: "physical",
    role: "display",
    video: { id: null, driveId: "1qfb-xu-2XCHtqWUVeCoYnkAFh57ZU9iu" },
    program: {
      hex: null,
      blocks: "guides/rgb-led-strip/blocks.png",
      driveId: "14PyuvOkJuGgxVF46vIireao3PHcnXmU-",
    },
    wiring: {
      order: "guides/rgb-led-strip/wiring-order.jpg",
      done: "guides/rgb-led-strip/wiring-done.jpg",
      wires: [
        { color: WIRE.red, key: "vcc" },
        { color: WIRE.black, key: "gnd" },
        { color: WIRE.yellow, key: "signal" },
        { key: "inOutPort" },
      ],
    },
    parts: {
      image: "guides/rgb-led-strip/parts.jpg",
      list: [
        { qty: 1, key: "microbitV2" },
        { qty: 1, key: "downloadCable" },
        { qty: 3, key: "alligatorClip" },
        { qty: 3, key: "jumperMM" },
        { qty: 1, key: "rgbStrip" },
      ],
    },
    troubleshootingStatus: "draft",
  },
  {
    slug: "expansion-board",
    componentKey: "microbitExpansionShield",
    kit: "robotics",
    role: "controller",
    video: { id: null, driveId: "1rsi2I25b1yTi7VLrosn12BtxYnMLPpBf" },
    program: {
      hex: null,
      blocks: "guides/expansion-board/blocks.png",
      driveId: "1WibxJAxpPitu1KbaT3sWoWwHQQA0fZSJ",
    },
    wiring: {
      ports: "guides/expansion-board/ports.jpg",
      done: "guides/expansion-board/wiring-done.jpg",
      wires: [
        { key: "gpio" },
        { key: "servoPort" },
        { key: "motorPort" },
        { key: "chargePort" },
      ],
    },
    parts: {
      image: "guides/expansion-board/parts.jpg",
      list: [
        { qty: 1, key: "microbitV2" },
        { qty: 1, key: "downloadCable" },
        { qty: 1, key: "expansionBoard" },
      ],
    },
    troubleshootingStatus: "draft",
  },
  {
    slug: "power-adapter",
    componentKey: "powerAdapterCharger",
    kit: "robotics",
    role: "power",
    video: { id: null, driveId: "1mWDs20Mmau0H5eQAhxlNEtIeIBJ3xrTY" },
    states: [
      { image: "guides/power-adapter/charging.jpg", key: "charging", color: WIRE.red },
      { image: "guides/power-adapter/charged.jpg", key: "charged", color: WIRE.green },
    ],
    troubleshootingStatus: "draft",
  },
  {
    slug: "potentiometer",
    componentKey: "potentiometerModule",
    kit: "robotics",
    role: "control",
    video: { id: null, driveId: "1XDu92Vc5aXyrZ_s3zNpniJzvvszHHjob" },
    program: {
      hex: null,
      blocks: "guides/potentiometer/blocks.png",
      driveId: "1M2-nJmbOoJywddJb0dEh_Ucxw_-Vscsk",
    },
    wiring: {
      done: "guides/potentiometer/wiring-done.jpg",
      wires: [
        { key: "vcc" },
        { key: "gnd" },
        { key: "signal" },
      ],
    },
    parts: {
      image: "guides/potentiometer/parts.jpg",
      list: [
        { qty: 1, key: "microbitV2" },
        { qty: 1, key: "downloadCable" },
        { qty: 1, key: "expansionBoard" },
        { qty: 3, key: "jumperFF" },
        { qty: 1, key: "potentiometer" },
      ],
    },
    troubleshootingStatus: "draft",
  },
  {
    slug: "color-sensor",
    componentKey: "colorSensorModule",
    kit: "robotics",
    role: "sensor",
    video: { id: null, driveId: "1TZ2SvmiXFcIyQRN5EZ-XH_gpHkoCG8oD" },
    program: {
      hex: null,
      blocks: "guides/color-sensor/blocks.png",
      driveId: "1986dFvdEVYJXbpQXFNASY-tUTo6al1jT",
    },
    wiring: {
      done: "guides/color-sensor/wiring-done.jpg",
      wires: [
        { key: "vcc" },
        { key: "gnd" },
        { key: "sda" },
        { key: "scl" },
      ],
    },
    parts: {
      image: "guides/color-sensor/parts.jpg",
      list: [
        { qty: 1, key: "microbitV2" },
        { qty: 1, key: "downloadCable" },
        { qty: 1, key: "expansionBoard" },
        { qty: 4, key: "jumperFF" },
        { qty: 1, key: "colorSensor" },
      ],
    },
    troubleshootingStatus: "approved",
  },
  {
    slug: "soil-moisture",
    componentKey: "soilMoistureSensor",
    kit: "robotics",
    role: "sensor",
    video: { id: null, driveId: "1DwYIAnk3jdicp_wM3O87y4AW0ctiR1uW" },
    program: {
      hex: null,
      blocks: "guides/soil-moisture/blocks.png",
      driveId: "1k1M-azgiDaWvgKgqkC2w1pTfQdKpv8qW",
    },
    wiring: {
      done: "guides/soil-moisture/wiring-done.jpg",
      wires: [
        { key: "vcc" },
        { key: "gnd" },
        { key: "signal" },
      ],
    },
    parts: {
      image: "guides/soil-moisture/parts.jpg",
      list: [
        { qty: 1, key: "microbitV2" },
        { qty: 1, key: "downloadCable" },
        { qty: 1, key: "expansionBoard" },
        { qty: 3, key: "jumperFF" },
        { qty: 1, key: "soilSensor" },
      ],
    },
    troubleshootingStatus: "draft",
  },
  {
    slug: "servo-360",
    componentKey: "continuousRotationServo",
    kit: "robotics",
    role: "actuator",
    video: { id: null, driveId: "1Uqksk2obRmEMcyOYVoKLj-u5RdodZuTw" },
    program: {
      hex: null,
      blocks: "guides/servo-360/blocks.png",
      driveId: "1b4sfBPHXhrXh6L-DLA-ffWSW1suYeqss",
    },
    wiring: {
      order: "guides/servo-360/wiring-order.jpg",
      done: "guides/servo-360/wiring-done.jpg",
      wires: [
        { color: WIRE.red, key: "vcc" },
        { color: WIRE.brown, key: "gnd" },
        { color: WIRE.yellow, key: "signal" },
      ],
    },
    parts: {
      image: "guides/servo-360/parts.jpg",
      list: [
        { qty: 1, key: "microbitV2" },
        { qty: 1, key: "downloadCable" },
        { qty: 1, key: "expansionBoard" },
        { qty: 3, key: "jumperFF" },
        { qty: 1, key: "servo360" },
      ],
    },
    troubleshootingStatus: "draft",
  },
  {
    slug: "lcd-module",
    componentKey: "lcdModule",
    kit: "robotics",
    role: "display",
    video: { id: null, driveId: "1KG3swhXrzGAr40oDBzj0UMm03F20jyQP" },
    program: {
      hex: null,
      blocks: "guides/lcd-module/blocks.png",
      driveId: "1VyE1P7-N3xgmk1BPA8JB3_w-HZ9DqD2n",
    },
    wiring: {
      done: "guides/lcd-module/wiring-done.jpg",
      wires: [
        { key: "vcc" },
        { key: "gnd" },
        { key: "sda" },
        { key: "scl" },
      ],
    },
    parts: {
      image: "guides/lcd-module/parts.jpg",
      list: [
        { qty: 1, key: "microbitV2" },
        { qty: 1, key: "downloadCable" },
        { qty: 1, key: "expansionBoard" },
        { qty: 4, key: "jumperFF" },
        { qty: 1, key: "lcd" },
      ],
    },
    troubleshootingStatus: "draft",
  },
  {
    slug: "joystick",
    componentKey: "joystickModule",
    kit: "robotics",
    role: "control",
    video: { id: null, driveId: "1tIa2yb1ZFSOwydWTOG0FKoYwUd_6cROi" },
    program: {
      hex: null,
      blocks: "guides/joystick/blocks.png",
      driveId: "1ZZenLdHWJLgaz_JDPPd4aR0f53P1vARN",
    },
    wiring: {
      done: "guides/joystick/wiring-done.jpg",
      wires: [
        { key: "vcc" },
        { key: "gnd" },
        { key: "axisX" },
        { key: "axisY" },
        { key: "button" },
      ],
    },
    parts: {
      image: "guides/joystick/parts.jpg",
      list: [
        { qty: 1, key: "microbitV2" },
        { qty: 1, key: "downloadCable" },
        { qty: 1, key: "expansionBoard" },
        { qty: 5, key: "jumperFF" },
        { qty: 1, key: "joystick" },
      ],
    },
    troubleshootingStatus: "draft",
  },
  {
    slug: "ultrasonic",
    componentKey: "ultrasonicDistanceSensor",
    kit: "robotics",
    role: "sensor",
    video: { id: null, driveId: "1pR0VaYHWzKBoGxWjJHoE2IcXy9k_fngI" },
    program: {
      hex: null,
      blocks: "guides/ultrasonic/blocks.png",
      driveId: "1_4RTbfJ26QeQvssHmDuJWSlVG6OIUJ4D",
    },
    wiring: {
      done: "guides/ultrasonic/wiring-done.jpg",
      wires: [
        { key: "vcc" },
        { key: "gnd" },
        { key: "trig" },
        { key: "echo" },
      ],
    },
    parts: {
      image: "guides/ultrasonic/parts.jpg",
      list: [
        { qty: 1, key: "microbitV2" },
        { qty: 1, key: "downloadCable" },
        { qty: 1, key: "expansionBoard" },
        { qty: 4, key: "jumperFF" },
        { qty: 1, key: "ultrasonic" },
      ],
    },
    troubleshootingStatus: "draft",
  },
  {
    slug: "line-tracking",
    componentKey: "lineTrackingSensor",
    kit: "robotics",
    role: "sensor",
    video: { id: null, driveId: "1Zlf-3zeS9BcePLwED30_XZ2lEvgT_jjl" },
    program: {
      hex: null,
      blocks: "guides/line-tracking/blocks.png",
      driveId: "1xBLrSx_hLjqi_sw8mKm_UWMjMR3w7mWV",
    },
    wiring: {
      done: "guides/line-tracking/wiring-done.jpg",
      wires: [
        { key: "vcc" },
        { key: "gnd" },
        { key: "probeLeft" },
        { key: "probeCenter" },
        { key: "probeRight" },
      ],
    },
    parts: {
      image: "guides/line-tracking/parts.jpg",
      list: [
        { qty: 1, key: "microbitV2" },
        { qty: 1, key: "downloadCable" },
        { qty: 1, key: "expansionBoard" },
        { qty: 5, key: "jumperFF" },
        { qty: 1, key: "lineSensor" },
      ],
    },
    troubleshootingStatus: "draft",
  },
  {
    slug: "encoder-motor",
    componentKey: "dcEncoderMotors",
    kit: "robotics",
    role: "motor",
    video: { id: null, driveId: "1BbH3zLzmXfaa-AP6W7mQpeSrgwpRKvgd" },
    program: {
      hex: null,
      blocks: "guides/encoder-motor/blocks.png",
      driveId: "1KWg2vH6YB9gSLSTpMElQ3lANNFoetUw5",
    },
    wiring: {
      order: "guides/encoder-motor/wiring-order.jpg",
      wires: [{ key: "ph20" }],
    },
    parts: {
      image: "guides/encoder-motor/parts.jpg",
      list: [
        { qty: 1, key: "microbitV2" },
        { qty: 1, key: "downloadCable" },
        { qty: 1, key: "expansionBoard" },
        { qty: 1, key: "ph20Cable" },
        { qty: 1, key: "encoderMotor" },
      ],
    },
    troubleshootingStatus: "draft",
  },
];

/** Short labels: part names, wire legends and page furniture, per language. */
const MODULE_LABELS = {
  en: {
    skipToGuide: "Skip to the guide",
    breadcrumbSupport: "Support",
    breadcrumbResources: "Guides and Resources",
    videoTitle: "Operation steps video",
    videoPlay: "Play the video for",
    howTitle: "How it works",
    whereTitle: "Where it is used",
    partsTitle: "What you need",
    connectionTitle: "Connection",
    wiringOrder: "Wire order",
    wiringDone: "Completed connection",
    wiringPorts: "Board ports",
    wireLegend: "Wire colours",
    connectionLegend: "Connections to make",
    statesTitle: "Charging states",
    programTitle: "Program",
    programBlocks: "MakeCode blocks for this activity",
    downloadTitle: "Program file",
    downloadAction: "Download .hex",
    downloadHint: "Open the file on a computer and drag it onto the MICROBIT drive. Phones and tablets cannot copy the file to the board.",
    troubleshootingTitle: "Troubleshooting",
    stillTitle: "Still not working?",
    stillCopy: "Report the issue and the support team will follow up with the school.",
    stillAction: "Open a support request",
    onThisPage: "On this page",
    quickActions: "Quick actions",
    quickVideo: "Watch the video",
    quickHex: "Download the program",
    quickBack: "All component guides",
    relatedTitle: "Related guides",
    backToList: "Back to guides",
    partsNote: "Everything below comes with the kit.",
  },
  es: {
    breadcrumbSupport: "Soporte",
    skipToGuide: "Saltar a la guía",
    breadcrumbResources: "Guías y recursos",
    videoTitle: "Video de los pasos de operación",
    videoPlay: "Reproducir el video de",
    howTitle: "Cómo funciona",
    whereTitle: "Dónde se usa",
    partsTitle: "Qué necesita",
    connectionTitle: "Conexión",
    wiringOrder: "Orden de los cables",
    wiringDone: "Conexión terminada",
    wiringPorts: "Puertos de la placa",
    wireLegend: "Colores de los cables",
    connectionLegend: "Conexiones a realizar",
    statesTitle: "Estados de carga",
    programTitle: "Programa",
    programBlocks: "Bloques de MakeCode de esta actividad",
    downloadTitle: "Archivo del programa",
    downloadAction: "Descargar .hex",
    downloadHint: "Abra el archivo en una computadora y arrástrelo a la unidad MICROBIT. Los teléfonos y las tablets no pueden copiar el archivo a la placa.",
    troubleshootingTitle: "Diagnóstico",
    stillTitle: "¿Sigue sin funcionar?",
    stillCopy: "Reporte el problema y el equipo de soporte hará el seguimiento con la escuela.",
    stillAction: "Abrir un pedido de soporte",
    onThisPage: "En esta página",
    quickActions: "Acciones rápidas",
    quickVideo: "Ver el video",
    quickHex: "Descargar el programa",
    quickBack: "Todas las guías",
    relatedTitle: "Guías relacionadas",
    backToList: "Volver a las guías",
    partsNote: "Todo lo que sigue viene incluido en el kit.",
  },
  fr: {
    breadcrumbSupport: "Support",
    skipToGuide: "Aller au guide",
    breadcrumbResources: "Guides et ressources",
    videoTitle: "Vidéo des étapes d'utilisation",
    videoPlay: "Lire la vidéo de",
    howTitle: "Comment ça marche",
    whereTitle: "Où on l'utilise",
    partsTitle: "Ce qu'il vous faut",
    connectionTitle: "Connexion",
    wiringOrder: "Ordre des fils",
    wiringDone: "Connexion terminée",
    wiringPorts: "Ports de la carte",
    wireLegend: "Couleurs des fils",
    connectionLegend: "Connexions à réaliser",
    statesTitle: "États de charge",
    programTitle: "Programme",
    programBlocks: "Blocs MakeCode de cette activité",
    downloadTitle: "Fichier du programme",
    downloadAction: "Télécharger le .hex",
    downloadHint: "Ouvrez le fichier sur un ordinateur et faites-le glisser sur le lecteur MICROBIT. Les téléphones et tablettes ne peuvent pas copier le fichier sur la carte.",
    troubleshootingTitle: "Diagnostic",
    stillTitle: "Toujours en panne ?",
    stillCopy: "Signalez le problème et l'équipe de support assurera le suivi avec l'école.",
    stillAction: "Ouvrir une demande de support",
    onThisPage: "Sur cette page",
    quickActions: "Actions rapides",
    quickVideo: "Voir la vidéo",
    quickHex: "Télécharger le programme",
    quickBack: "Tous les guides",
    relatedTitle: "Guides associés",
    backToList: "Retour aux guides",
    partsNote: "Tout ce qui suit est fourni avec le kit.",
  },
  pt: {
    breadcrumbSupport: "Suporte",
    skipToGuide: "Ir para o guia",
    breadcrumbResources: "Guias e recursos",
    videoTitle: "Vídeo dos passos de operação",
    videoPlay: "Reproduzir o vídeo de",
    howTitle: "Como funciona",
    whereTitle: "Onde é usado",
    partsTitle: "O que você precisa",
    connectionTitle: "Conexão",
    wiringOrder: "Ordem dos cabos",
    wiringDone: "Conexão concluída",
    wiringPorts: "Portas da placa",
    wireLegend: "Cores dos cabos",
    connectionLegend: "Conexões a realizar",
    statesTitle: "Estados de carga",
    programTitle: "Programa",
    programBlocks: "Blocos do MakeCode desta atividade",
    downloadTitle: "Arquivo do programa",
    downloadAction: "Baixar .hex",
    downloadHint: "Abra o arquivo em um computador e arraste-o para a unidade MICROBIT. Telefones e tablets não conseguem copiar o arquivo para a placa.",
    troubleshootingTitle: "Diagnóstico",
    stillTitle: "Ainda não funciona?",
    stillCopy: "Relate o problema e a equipe de suporte fará o acompanhamento com a escola.",
    stillAction: "Abrir um pedido de suporte",
    onThisPage: "Nesta página",
    quickActions: "Ações rápidas",
    quickVideo: "Ver o vídeo",
    quickHex: "Baixar o programa",
    quickBack: "Todos os guias",
    relatedTitle: "Guias relacionados",
    backToList: "Voltar aos guias",
    partsNote: "Tudo o que segue vem incluído no kit.",
  },
};

const PART_NAMES = {
  en: {
    microbitV2: "micro:bit V2 mainboard",
    downloadCable: "Download cable",
    alligatorClip: "Alligator clip wires",
    jumperMM: "Male-to-male jumper wires",
    jumperFF: "Female-to-female jumper wires",
    expansionBoard: "Micro:bit expansion board",
    ph20Cable: "PH2.0-6P terminal cable",
    servo180: "180° servo motor",
    servo360: "360° servo motor",
    rgbStrip: "RGB LED flexible strip",
    potentiometer: "Potentiometer module",
    colorSensor: "Color sensor module",
    soilSensor: "Soil moisture sensor",
    lcd: "LCD display module",
    joystick: "Joystick module",
    ultrasonic: "Ultrasonic distance module",
    lineSensor: "Line tracking sensor",
    encoderMotor: "DC encoder motor",
  },
  es: {
    microbitV2: "placa micro:bit V2",
    downloadCable: "Cable de descarga",
    alligatorClip: "Cables con pinza cocodrilo",
    jumperMM: "Cables jumper macho-macho",
    jumperFF: "Cables jumper hembra-hembra",
    expansionBoard: "Placa de expansión micro:bit",
    ph20Cable: "Cable terminal PH2.0-6P",
    servo180: "Servomotor 180°",
    servo360: "Servomotor 360°",
    rgbStrip: "Tira LED RGB flexible",
    potentiometer: "Módulo potenciómetro",
    colorSensor: "Módulo sensor de color",
    soilSensor: "Sensor de humedad del suelo",
    lcd: "Módulo de pantalla LCD",
    joystick: "Módulo joystick",
    ultrasonic: "Módulo ultrasónico de distancia",
    lineSensor: "Sensor seguidor de línea",
    encoderMotor: "Motor DC con encoder",
  },
  fr: {
    microbitV2: "carte micro:bit V2",
    downloadCable: "Câble de téléchargement",
    alligatorClip: "Fils à pinces crocodile",
    jumperMM: "Fils jumper mâle-mâle",
    jumperFF: "Fils jumper femelle-femelle",
    expansionBoard: "Carte d'extension micro:bit",
    ph20Cable: "Câble terminal PH2.0-6P",
    servo180: "Servomoteur 180°",
    servo360: "Servomoteur 360°",
    rgbStrip: "Ruban LED RVB flexible",
    potentiometer: "Module potentiomètre",
    colorSensor: "Module capteur de couleur",
    soilSensor: "Capteur d'humidité du sol",
    lcd: "Module d'affichage LCD",
    joystick: "Module joystick",
    ultrasonic: "Module de distance ultrasonique",
    lineSensor: "Capteur suiveur de ligne",
    encoderMotor: "Moteur CC avec encodeur",
  },
  pt: {
    microbitV2: "placa micro:bit V2",
    downloadCable: "Cabo de download",
    alligatorClip: "Cabos com garra jacaré",
    jumperMM: "Cabos jumper macho-macho",
    jumperFF: "Cabos jumper fêmea-fêmea",
    expansionBoard: "Placa de expansão micro:bit",
    ph20Cable: "Cabo terminal PH2.0-6P",
    servo180: "Servomotor 180°",
    servo360: "Servomotor 360°",
    rgbStrip: "Fita LED RGB flexível",
    potentiometer: "Módulo potenciômetro",
    colorSensor: "Módulo sensor de cor",
    soilSensor: "Sensor de umidade do solo",
    lcd: "Módulo de display LCD",
    joystick: "Módulo joystick",
    ultrasonic: "Módulo ultrassônico de distância",
    lineSensor: "Sensor seguidor de linha",
    encoderMotor: "Motor DC com encoder",
  },
};

const WIRE_LABELS = {
  en: {
    vcc: "VCC — power positive",
    gnd: "GND — ground",
    signal: "Signal",
    sda: "SDA — I2C data",
    scl: "SCL — I2C clock",
    trig: "Trig — pulse out",
    echo: "Echo — pulse in",
    axisX: "X axis",
    axisY: "Y axis",
    button: "Push button",
    probeLeft: "Left probe",
    probeCenter: "Centre probe",
    probeRight: "Right probe",
    inOutPort: "Input port and output port markings",
    gpio: "GPIO ports",
    servoPort: "Servo ports",
    motorPort: "Encoder motor ports",
    chargePort: "Charging port and status LED",
    ph20: "PH2.0-6P connector, single orientation",
  },
  es: {
    vcc: "VCC — positivo de alimentación",
    gnd: "GND — tierra",
    signal: "Señal",
    sda: "SDA — datos I2C",
    scl: "SCL — reloj I2C",
    trig: "Trig — pulso de salida",
    echo: "Echo — pulso de entrada",
    axisX: "Eje X",
    axisY: "Eje Y",
    button: "Pulsador",
    probeLeft: "Sonda izquierda",
    probeCenter: "Sonda central",
    probeRight: "Sonda derecha",
    inOutPort: "Marcas de puerto de entrada y de salida",
    gpio: "Puertos GPIO",
    servoPort: "Puertos de servo",
    motorPort: "Puertos de motor con encoder",
    chargePort: "Puerto de carga y LED de estado",
    ph20: "Conector PH2.0-6P, una sola orientación",
  },
  fr: {
    vcc: "VCC — pôle positif",
    gnd: "GND — masse",
    signal: "Signal",
    sda: "SDA — données I2C",
    scl: "SCL — horloge I2C",
    trig: "Trig — impulsion émise",
    echo: "Echo — impulsion reçue",
    axisX: "Axe X",
    axisY: "Axe Y",
    button: "Bouton-poussoir",
    probeLeft: "Sonde gauche",
    probeCenter: "Sonde centrale",
    probeRight: "Sonde droite",
    inOutPort: "Repères de port d'entrée et de sortie",
    gpio: "Ports GPIO",
    servoPort: "Ports servo",
    motorPort: "Ports moteur à encodeur",
    chargePort: "Port de charge et LED d'état",
    ph20: "Connecteur PH2.0-6P, une seule orientation",
  },
  pt: {
    vcc: "VCC — positivo da alimentação",
    gnd: "GND — terra",
    signal: "Sinal",
    sda: "SDA — dados I2C",
    scl: "SCL — clock I2C",
    trig: "Trig — pulso de saída",
    echo: "Echo — pulso de entrada",
    axisX: "Eixo X",
    axisY: "Eixo Y",
    button: "Botão",
    probeLeft: "Sonda esquerda",
    probeCenter: "Sonda central",
    probeRight: "Sonda direita",
    inOutPort: "Marcas de porta de entrada e de saída",
    gpio: "Portas GPIO",
    servoPort: "Portas de servo",
    motorPort: "Portas de motor com encoder",
    chargePort: "Porta de carga e LED de estado",
    ph20: "Conector PH2.0-6P, orientação única",
  },
};

const STATE_LABELS = {
  en: { charging: "Charging — the status LED is red", charged: "Fully charged — the status LED is green" },
  es: { charging: "Cargando — el LED de estado está rojo", charged: "Carga completa — el LED de estado está verde" },
  fr: { charging: "En charge — la LED d'état est rouge", charged: "Charge complète — la LED d'état est verte" },
  pt: { charging: "Carregando — o LED de estado está vermelho", charged: "Carga completa — o LED de estado está verde" },
};
